<?php
include ("../constants/routes.php");
// include($components_file_error_handler);
include ($constants_file_dbconnect);
include ($constants_file_session_admin);
include ($constants_variables);

if (isset($_POST['addEmployeeInfo'])) {
    $birthplace = sanitizeInput($_POST['birthplace'] ?? '');
    $height = sanitizeInput($_POST['height'] ?? '');
    $weight = sanitizeInput($_POST['weight'] ?? '');
    $bloodtype = sanitizeInput($_POST['bloodtype'] ?? '');
    $gsis = sanitizeInput($_POST['gsis'] ?? '');
    $pagibig = sanitizeInput($_POST['pagibig'] ?? '');
    $philhealth = sanitizeInput($_POST['philhealth'] ?? '');
    $sss = sanitizeInput($_POST['sss'] ?? '');
    $tin = sanitizeInput($_POST['tin'] ?? '');
    $agency = sanitizeInput($_POST['agency'] ?? '');
    $civilStatus = sanitizeInput($_POST['civilStatus'] ?? '');
    $houseNo = sanitizeInput($_POST['houseNo'] ?? '');
    $street = sanitizeInput($_POST['street'] ?? '');
    $subdivision = sanitizeInput($_POST['subdivision'] ?? '');
    $city = sanitizeInput($_POST['city'] ?? '');
    $province = sanitizeInput($_POST['province'] ?? '');
    $zipCode = sanitizeInput($_POST['zipCode'] ?? '');
    $telephone = sanitizeInput($_POST['telephone'] ?? '');
    $mobile = sanitizeInput($_POST['mobile'] ?? '');

    $spousesurname = sanitizeInput($_POST['spouseSurname'] ?? '');
    $spousename = sanitizeInput($_POST['spouseName'] ?? '');
    $spousemiddlename = sanitizeInput($_POST['spouseMiddleName'] ?? '');
    $spousenameExtension = sanitizeInput($_POST['spouseNameExtension'] ?? '');
    $spouseOccupation = sanitizeInput($_POST['spouseOccupation'] ?? '');
    $spouseEmployer = sanitizeInput($_POST['spouseEmployer'] ?? '');
    $spouseBusinessAddress = sanitizeInput($_POST['spouseBusinessAddress'] ?? '');
    $spouseTelephone = sanitizeInput($_POST['spouseTelephone'] ?? '');
    $numberOfChildren = sanitizeInput($_POST['numberOfChildren'] ?? '');
    $fathersSurname = sanitizeInput($_POST['fathersSurname'] ?? '');
    $fathersFirstname = sanitizeInput($_POST['fathersFirstname'] ?? '');
    $fathersMiddlename = sanitizeInput($_POST['fathersMiddlename'] ?? '');
    $fathersnameExtension = sanitizeInput($_POST['fathersnameExtension'] ?? '');
    $MSurname = sanitizeInput($_POST['MSurname'] ?? '');
    $MName = sanitizeInput($_POST['MName'] ?? '');
    $MMName = sanitizeInput($_POST['MMName'] ?? '');
    
    $graduateStudies = sanitizeInput($_POST['graduateStudies'] ?? '');
    $elemschoolName = sanitizeInput($_POST['elemschoolName'] ?? '');
    $elembasicEducation = sanitizeInput($_POST['elembasicEducation'] ?? '');
    $elemhighestLevel = sanitizeInput($_POST['elemhighestLevel'] ?? '');
    $elemScholarship = sanitizeInput($_POST['elemScholarship'] ?? '');
    $elemPeriod = sanitizeInput($_POST['elemPeriod'] ?? '');
    $elemperiodEnd = sanitizeInput($_POST['elemperiodEnd'] ?? '');
    $secondschoolName = sanitizeInput($_POST['secondschoolName'] ?? '');
    $secondbasicEducation = sanitizeInput($_POST['secondbasicEducation'] ?? '');
    $secondhighestLevel = sanitizeInput($_POST['secondhighestLevel'] ?? '');
    $secondScholarship = sanitizeInput($_POST['secondScholarship'] ?? '');
    $secondPeriod = sanitizeInput($_POST['secondPeriod'] ?? '');
    $secondperiodEnd = sanitizeInput($_POST['secondperiodEnd'] ?? '');
    $vocationalschoolName = sanitizeInput($_POST['vocationalschoolName'] ?? '');
    $vocationalbasicEducation = sanitizeInput($_POST['vocationalbasicEducation'] ?? '');
    $vocationalhighestLevel = sanitizeInput($_POST['vocationalhighestLevel'] ?? '');
    $vocationalScholarship = sanitizeInput($_POST['vocationalScholarship'] ?? '');
    $vocationalPeriod = sanitizeInput($_POST['vocationalPeriod'] ?? '');
    $vocationalperiodEnd = sanitizeInput($_POST['vocationalperiodEnd'] ?? '');
    $collegeschoolName = sanitizeInput($_POST['collegeschoolName'] ?? '');
    $collegebasicEducation = sanitizeInput($_POST['collegebasicEducation'] ?? '');
    $collegehighestLevel = sanitizeInput($_POST['collegehighestLevel'] ?? '');
    $collegeScholarship = sanitizeInput($_POST['collegeScholarship'] ?? '');
    $collegePeriod = sanitizeInput($_POST['collegePeriod'] ?? '');
    $collegeperiodEnd = sanitizeInput($_POST['collegeperiodEnd'] ?? '');

    echo $birthplace;
    echo $height;
    echo $weight;
    echo $bloodtype;
    echo $gsis;
    echo $pagibig;
    echo $philhealth;
    echo $sss;
    echo $tin;
    echo $agency;
    echo $civilStatus;
    echo $houseNo;
    echo $street;
    echo $subdivision;
    echo $city;
    echo $province;
    echo $zipCode;
    echo $telephone;
    echo $mobile;
    echo $spousesurname;
    echo $spousename;
    echo $spousemiddlename;
    echo $spousenameExtension;
    echo $spouseOccupation;
    echo $spouseEmployer;
    echo $spouseBusinessAddress;
    echo $spouseTelephone;
    echo $numberOfChildren;
    echo $fathersSurname;
    echo $fathersFirstname;
    echo $fathersMiddlename;
    echo $MSurname;
    echo $MName;
    echo $MMName;
    echo $graduateStudies;
    echo $elemschoolName;
    echo $elembasicEducation;
    echo $elemhighestLevel;
    echo $elemScholarship;
    echo $elemPeriod;
    echo $elemperiodEnd;
    echo $secondschoolName;
    echo $secondbasicEducation;
    echo $secondhighestLevel;
    echo $secondScholarship;
    echo $secondPeriod;
    echo $secondperiodEnd;
    echo $vocationalschoolName;
    echo $vocationalbasicEducation;
    echo $vocationalhighestLevel;
    echo $vocationalScholarship;
    echo $vocationalPeriod;
    echo $vocationalperiodEnd;
    echo $collegeschoolName;
    echo $collegebasicEducation;
    echo $collegehighestLevel;
    echo $collegeScholarship;
    echo $collegePeriod;
    echo $collegeperiodEnd;
}


?>